# -*- coding: utf-8 -*-
"""MemData.ipynb

Automatically generated by Colab.
"""
# pip install address-parser

# pip install phonetics

from address_parser import Parser
# Create a parser object
parser = Parser()
# Parse an address string
adr = parser.parse("123 Main St. Suite 100 Chicago, IL")
# Access the parsed components
print(adr.number.number) # House number
print(adr.road.name) # Street name
print(adr.locality.city) # City
print(adr.locality.state) # State
print(adr.locality.zip) # ZIP code

import pandas as pd
# Load the Excel file
df = pd.read_excel("ACTIVE.xlsx")

# Save it as a CSV file
df.to_csv("ACTIVE.csv", index=False)

df = pd.read_csv("ACTIVE.csv", skiprows=11)
df.drop(columns=['Unnamed: 0',
                 'Community Group: Created Date',
                 'Linked Chapter Account: Phone'], axis=1, inplace=True)

print('Current DataFrame Columns:', df.columns)
# print(df.columns)
print(df['Linked Chapter Account: Zone'].value_counts(dropna=False))

import pandas as pd

# The address_parser was not effectively populating parsed_state and parsed_country for this dataset.
# We will explicitly avoid using it to create new columns, and instead rely on existing data.
# The function `get_address_details` and `address_parser` initialization are kept here if you
# wish to experiment with them later, but their output is no longer assigned to filtered_df.
from address_parser import Parser
parser = Parser()
def get_address_details(address_line):
    if pd.isna(address_line):
        return None, None
    try:
        adr = parser.parse(address_line)
        state = adr.locality.state if adr and adr.locality else None
        country = adr.locality.country if adr and adr.locality else None
        return state, country
    except Exception:
        return None, None

# Remove or comment out the line that previously created 'parsed_state' and 'parsed_country'
# filtered_df[['parsed_state', 'parsed_country']] = filtered_df['Linked Chapter Account: Billing Address Line 1'].apply(lambda x: pd.Series(get_address_details(x)))

# Ensure 'parsed_state' and 'parsed_country' columns do not exist or are handled if later referenced.
# For now, we are explicitly NOT creating them for filtering purposes.

# Re-display info to show that parsed columns are not being used
# We are displaying filtered_df.head() as the last output of this cell to maintain consistency
filtered_df.shape

def export_to_txt(filename, content):
    """
    Writes text content to a .txt file safely.
    """
    # Basic validation
    if not isinstance(filename, str) or not filename.endswith(".txt"):
        raise ValueError("Filename must be a string ending with .txt")
    if not isinstance(content, str):
        raise ValueError("Content must be a string")

    try:
        # Use 'with' to ensure file closes automatically
        with open(filename, "w", encoding="utf-8") as file:
            file.write(content)
        print(f"Successfully wrote to {filename}")

    except OSError as e:
        # Handles issues like permission errors or invalid paths
        print(f"File write failed: {e}")

# Example usage
if __name__ == "__main__":
    data = "This is the text that will be exported to the file."
    export_to_txt("output.txt", data)

# Define the target regions
us_states = ['MA', 'CT', 'VT', 'ME', 'NJ', 'NY', 'RI', 'MASSACHUSETTS', 'CONNECTICUT', 'VERMONT', 'MAINE', 'NEW JERSEY', 'NEW YORK', 'RHODE ISLAND', 'ALABAMA']

# For 'East Canada', we will check for 'Canada' as the country.
# For 'West Africa', we will check for common West African countries.
west_african_countries = ['NIGERIA', 'GHANA', 'SENEGAL', 'IVORY COAST', 'CÔTE D’IVOIRE', 'MALI', 'BURKINA FASO', 'NIGER', 'LIBERIA', 'SIERRA LEONE', 'TOGO', 'BENIN', 'GAMBIA', 'GUINEA', 'GUINEA-BISSAU', 'MAURITANIA']

# Create the filtering conditions directly using the existing DataFrame columns
# Convert to uppercase for case-insensitive comparison and handle NaN values with fillna(False)
condition_us_states = filtered_df['Linked Chapter Account: Billing State/Province'].str.upper().isin(us_states).fillna(False)
condition_canada = (filtered_df['Linked Chapter Account: Billing Country'].str.upper() == 'CANADA').fillna(False)
condition_west_africa = filtered_df['Linked Chapter Account: Billing Country'].str.upper().isin([c.upper() for c in west_african_countries]).fillna(False)

# Combine all conditions
final_filtered_df = filtered_df[condition_us_states | condition_canada | condition_west_africa]

# Convert the 'Community Group: Community Group Name' Series to a list and then join with newlines
community_names_to_export = "\n".join(final_filtered_df['Community Group: Community Group Name'].astype(str).tolist())

# Export the full community names to active.txt
export_to_txt("not_active.txt", community_names_to_export)